# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c9605e0677aa51100b71d8ef98d9d7b45919a5d703d2ba6178ffb823a5445c2829d60263878ea0782f8085b160d78d881df7ab79daed870cac3d37bf508e903

test:
  secret_key_base: 236c4e02a1b620461b1d749cfe3472e2cf6ab1f9216f3259d80fa93b43eab4213906de368191e5514aa41c65849a4db7d671f141388089c0d27a8695fe132c1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
